version: "3.8"
services: 
  nginx: 
    container_name: nginx_1
    image: nginx:latest
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes: 
    - type: bind 
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
    - front-end 

  front-end: 
    container_name: front_end_api
    build: ./front_end_api
    depends_on: 
    - character_api
    - class_api 

  character_api: 
    container_name: character_api
    build: ./character_api


  class_api:
    container_name: class_api 
    build: ./class_api 
    